# SPAM EMAIL CLASSIFIACTION

In [3]:
#Importing libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [4]:
#Load Data
df = pd.read_csv('emails.csv')

In [5]:
#showing the csv file
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [6]:
#print the shape
df.shape

(5728, 2)

In [7]:
#Get the column name
df.columns

Index(['text', 'spam'], dtype='object')

In [8]:
#checking for duplicate and removing them
df.drop_duplicates(inplace = True)

In [9]:
#show the new shape
df.shape

(5695, 2)

In [10]:
#show the no. of missing data(NAN,na..)
df.isnull().sum()

text    0
spam    0
dtype: int64

In [11]:
#download the stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\krishaant.S.H\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [15]:
def process_text(text):
    
    #1 Remove punchuations
    #2 Remove stopwords
    #3 return list of clean text
    
    nopunc = [char for char in text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    
    clean_words = [word for word in nopunc.split() if word.lower not in stopwords.words('english')]
    
    return clean_words

In [16]:
#show the tokenization ( list of tokens)
df['text'].head(5).apply(process_text)

0    [Subject, naturally, irresistible, your, corpo...
1    [Subject, the, stock, trading, gunslinger, fan...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, do, not, have, money, get, software,...
Name: text, dtype: object

In [18]:
#convert a collection of text to matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer
message_bow = CountVectorizer(analyzer = process_text).fit_transform(df['text'])

In [21]:
#split the data into 80% training set and 20% test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(message_bow, df['spam'],test_size =0.20,random_state = 0)

In [22]:
#Get the shape of message_bow
message_bow.shape

(5695, 37380)

In [23]:
#Create and train the Randomforest classifier
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [24]:
#print the predicted value and the actual values
print(model.predict(x_train))
print(y_train.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [28]:
#Evaluate the model on training dataset
from sklearn.metrics import classification_report, confusion_matrix ,accuracy_score
pred =  model.predict(x_train)
print(classification_report(y_train,pred))
print()
print('Confusion Matrix: \n',confusion_matrix(y_train,pred))
print()
print('Accuracy: ',accuracy_score(y_train,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       1.00      1.00      1.00      1099

    accuracy                           1.00      4556
   macro avg       1.00      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


Confusion Matrix: 
 [[3457    0]
 [   0 1099]]

Accuracy:  1.0


In [31]:
#print the predicted value and the actual values for test dataset
print(model.predict(x_test))
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [29]:
#Evaluate the model on test  dataset
from sklearn.metrics import classification_report, confusion_matrix ,accuracy_score
pred =  model.predict(x_test)
print(classification_report(y_test,pred))
print()
print('Confusion Matrix: \n',confusion_matrix(y_test,pred))
print()
print('Accuracy: ',accuracy_score(y_test,pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98       870
           1       1.00      0.89      0.94       269

    accuracy                           0.97      1139
   macro avg       0.98      0.95      0.96      1139
weighted avg       0.98      0.97      0.97      1139


Confusion Matrix: 
 [[870   0]
 [ 29 240]]

Accuracy:  0.974539069359087
